### ISSUE TITLE
Issue with String.empty

### ISSUE THREAD

**Issue by djechelon** [JakeGinnivan/ExpressionToString#14]
Hi,

I just found an issue related to `String.Empty`.

I had `NullReferenceException` on a complex query on line 76 of `ExpressionStringBuilder`. Thanks to debug I found that the "guilty" node is `String.Empty`. Source expression in fact is `new string[] { "0", "1", String.Empty }.Contains(x.A.A42)` (translated from SQL ` A42 IN (0,1,'')`.

I fixed myself the problem by adding a specific check, but I don't believe this is a permanent solution, so I will **not** submit a PR for now

Fix is for `VisitMember` method

            if (node.Expression == null)
            {
                Out(node.Member.ToString());
            }
            else if (node.Expression.NodeType == ExpressionType.Constant)

I would like to ask feedback about it (it produces `System.String Empty` as output).

Thank you.

**Comment by JakeGinnivan** [comment]
Thanks for the issue, I will deploy the fix later today
