### ISSUE TITLE
Use operator symbols

### ISSUE THREAD

**Issue by ByteBlast** [JakeGinnivan/ExpressionToString#3]
Consider the following expression:
```c#
Expression<Func<string, bool>> func = text => text.StartsWith("E") && text.EndsWith("g");
var result = ExpressionStringBuilder.ToString(func);
```

It produces the following result:

    (text) => (text.StartsWith("E") AndAlso text.EndsWith("g"))

What do you think about making it produce:

    (text) => (text.StartsWith("E") && text.EndsWith("g"))

In other words, I would like it if the function replaced the words `AndAlso` with the symbols `&&`. Similarly, `And` would become `&` and so on. In my opinion this better reflects the original expression.

**Comment by JakeGinnivan** [comment]
See https://github.com/JakeGinnivan/ExpressionToString/blob/master/src/ExpressionToString/ExpressionStringBuilder.cs#L240

I think it is just `AndAlso` which suffers from this.

**Comment by JakeGinnivan** [comment]
`OrElse` is wrong too, I wasn't sure what that operator was off the top of my head when doing it :P #lazy

**Comment by ByteBlast** [comment]
I will fix them for you.
